services:

  php:
    volumes:
      - ./src:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./composer.json:/composer.json
      - ./vendor:/vendor
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env


  webserver:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

 


  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${DB_PASSCHOICE}"
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      PMA_PORT: "3306"
    networks:
      - app-network

networks: #network for all running services
  app-network:
    driver: bridge

volumes:
  db_data: